### ISSUE TITLE
test(plugins/dropbot): test installation of DropBot Python 3 driver

### ISSUE THREAD

**Issue by cfobel** [sci-bots/microdrop-3.0#30]
See also: https://trello.com/c/V0d60ErM

-----------------------------------

# Test DropBot Python 3 driver

 1. Download [db-py3-test.build.yaml.txt](https://github.com/sci-bots/microdrop-3/files/1760582/db-py3-test.build.yaml.txt)
 2. In a **`win-32` Conda environment**, run: `conda env create --file db-py3-test.build.yaml.txt -n db-py3-test`
 3. Activate the conda environment: `activate db-py3-test`
 4. Run `python -c "from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir"`
 5. Plug in DropBot by USB and run: `dropbot-self-test test`

# Expected output

 - Step **4** should execute with out raising an exception
 - Output from step **5** should be similar to the following:

```markdown
listening
connected to COM15
system_info: 0.3 s
test_system_metrics: 0.0 s
test_i2c: 1.8 s
test_voltage: 12.2 s
test_shorts: 1.4 s
test_on_board_feedback_calibration: 1.8 s
test_channels: 9.3 s
**Total time: 26.7 s**
# DropBot self test (*2018-02-27T00:23:33*)

------------------------------------------------------------------------

# Control board (UUID: `0000b1e8-1700-05b4-0200-3900454e1841`) #

## Properties ##

 - **base_node_software_version**: `b'0.42.1'`
 - **package_name**: `b'dropbot'`
 - **display_name**: `b'DropBot'`
 - **manufacturer**: `b'Sci-Bots Inc.'`
 - **url**: `b'http://gitlab.com/sci-bots/dropbot.py.git'`
 - **software_version**: `b'1.46+25.g8c03b5f'`

## Config ##

 - **i2c_address**: `31`
 - **switching_board_i2c_address**: `32`
 - **R7**: `9623.3994140625`
 - **pot_max**: `52779.0390625`
 - **max_voltage**: `140.0`
 - **min_frequency**: `100.0`
 - **max_frequency**: `10000.0`
 - **id**: ``
 - **capacitance_n_samples**: `50`

**soft i2c scan**: `[44]`
**number of channels**: `120`

------------------------------------------------------------------------

# System Metrics: #


 - **temperature**: `39.99 degrees C`
 - **analog_reference**: `3.32 V`
 - **voltage_limit**: `156.62 V`

------------------------------------------------------------------------

# I2C scan: #

 - **`32`**: b'HV Switching Board' vb'3.1', firmware: vb'0.10', uuid: `651d3f89-ccd0-4ed6-b473-1adb680861bb`
 - **`33`**: b'HV Switching Board' vb'3.1', firmware: vb'0.10', uuid: `dd0af713-e8cb-41aa-8cdb-568e3f6f90f2`
 - **`34`**: b'HV Switching Board' vb'3.1', firmware: vb'0.10', uuid: `37d876c7-4468-4aef-88e0-261929b69579`
 - **`80`**: 120-channel-pogo-pin-board v3.3, uuid: `a5943278-0d4b-4755-b717-f477171892d3`
 - **`81`**: dropbot-front-panel v3.1, uuid: `d751d6eb-8567-46a5-aeb8-99fe5714d7b3`

------------------------------------------------------------------------

# Test voltage results: #

 - **Output voltages**:

                       0       1       2        3        4
        target    24.8 V  53.6 V  82.4 V  111.2 V  140.0 V
        measured  24.6 V  52.3 V  81.8 V  111.3 V  143.0 V
 - **Root-mean-squared (RMS) error**: 1.5%

------------------------------------------------------------------------

# Test shorts results: #

 - No shorts.

------------------------------------------------------------------------

# Test on-board feedback calibration results: #

 - **Measured capacitance**:

                       0        1         2         3
        nominal    0.0 F  10.0 pF  100.0 pF  470.0 pF
        measured  1.4 pF  10.5 pF  108.0 pF  507.9 pF

------------------------------------------------------------------------

# Test channels results: #

**All 120 channels passed.**
disconnected from COM15
```

**Comment by cfobel** [comment]
@Lucaszw I encountered the following exception when executing `dropbot-self-test test` as outlined above in the **Test DropBot Python 3 driver** section:

```python
Traceback (most recent call last):
  File "C:\Users\chris\Miniconda2-x86\envs\db-py3-test.build\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\chris\Miniconda2-x86\envs\db-py3-test.build\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\chris\Miniconda2-x86\envs\db-py3-test.build\lib\site-packages\dropbot\bin\self_test.py", line 15, in <module>
    from ..self_test import (format_system_info_results, format_test_i2c_results,
  File "C:\Users\chris\Miniconda2-x86\envs\db-py3-test.build\lib\site-packages\dropbot\self_test.py", line 9, in <module>
    import matplotlib.pyplot
  File "C:\Users\chris\Miniconda2-x86\envs\db-py3-test.build\lib\site-packages\matplotlib\pyplot.py", line 32, in <module>
    import matplotlib.colorbar
  File "C:\Users\chris\Miniconda2-x86\envs\db-py3-test.build\lib\site-packages\matplotlib\colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "C:\Users\chris\Miniconda2-x86\envs\db-py3-test.build\lib\site-packages\matplotlib\contour.py", line 21, in <module>
    import matplotlib.font_manager as font_manager
  File "C:\Users\chris\Miniconda2-x86\envs\db-py3-test.build\lib\site-packages\matplotlib\font_manager.py", line 58, in <module>
    from matplotlib import afm, cbook, ft2font, rcParams, get_cachedir
ImportError: DLL load failed: The specified procedure could not be found.
```

# Workaround

I was able to work around the issue using the following steps:

 1. `conda uninstall --force matplotlib`
 2. `pip install matplotlib==2.1.2`

@Lucaszw , please let me know if this workaround is required on your computer as well.  I am packaging up an alternate `matplotlib` Conda package just in case.

**Comment by cfobel** [comment]
**Update** Note that I do not receive any DLL exception when performing step **4** of section **Test DropBot Python 3 driver** under a Python 3.6 Windows **_64-bit_** Conda environment.
